services:
  node-app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - '8080:3000'
      - '8081:81'
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - monitoring

  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    ports:
      - 4318:4318
      - 16686:16686
    networks:
      - monitoring

  elasticsearch:
    image: elasticsearch:8.17.0
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=admin
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./elasticsearch/conf.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    networks:
      - monitoring

  filebeat:
    image: elastic/filebeat:8.17.0
    user: root
    command: ['--strict.perms=false']
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./filebeat/conf.yml:/usr/share/filebeat/filebeat.yml
    networks:
      - monitoring

  logstash:
    image: logstash:8.17.0
    ports:
      - 5044:5044
      - 9600:9600
    volumes:
      - ./log/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
      - filebeat
    networks:
      - monitoring

  kibana:
    image: kibana:8.17.0
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    volumes:
      - ./kibana/conf.yml:/usr/share/kibana/config/kibana.yml:ro
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
  esdata:
    driver: local
